# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05f68a7f8262b143cb57ab3704377c8dbf5a84f99e155a44c09302d32a2dc890ae33f388954b97f37eaec3ed418cde3ca52587624279166eb5d027bb4b4f4a90

test:
  secret_key_base: d20d8ed4946d122aa688d17153fd3735dd9695e41b8dd9d7082fe7f71f58d5d66f9c0e5521875868c1984d69096c0d9d79be545d9beae0e374d47f04b6a8da4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
